### ISSUE TITLE
Authenticate Resources

### ISSUE THREAD

**Issue by tagnotfound** [gate-sso/gate#97] opened 2018-03-11 16:32 UTC
Authenticate the below resources with an API token
/users/search?q=g
/groups/search?q=g
/host_machines/search?q=g
/vpns/search?q=g

Presently there is no authentication present.

Apart from this also do a check for all calls that aren't web based, that is its api based and apply the api token authentication for it.

**Comment by giosakti** [comment] 2018-03-12 14:28
@ajeygore can you advise on this? Now that we have encrypted user token, we can't use it anymore by embedding them on layout. 

Should we create a new kind of token/secret that is more restricted and specifically created for accessing utility APIs like these?

**Comment by ajeygore** [comment] 2018-03-14 02:53
Why do you want to expose search APIs?

**Comment by giosakti** [comment] 2018-03-14 03:28
these APIs are necessary for autocomplete to function

**Comment by ajeygore** [comment] 2018-03-14 04:32
Let’s talk about it, how can we do these APIs with authentication. I am right now disabling this APIs, but Tests didn’t fail :-(

**Comment by phoenix-labs** [comment] 2018-03-14 04:55
Ajey / gio my only point is all endpoints should be validated by sessions or API tokens

**Comment by tagnotfound** [comment] 2018-03-14 05:02
Ajey / gio my only point is all endpoints should be validated by sessions or API tokens

**Comment by ajeygore** [comment] 2018-03-14 05:06
Yes, we will be validating with all sessions tokens, I have already put patch there and committed the code, will work with Gio today and close it. Thanks for raising it.

Ajey

**Comment by giosakti** [comment] 2018-03-14 06:12
with Ajey's latest commit, this should be secured because Devise already taking care of it. I just confirmed that Devise will check the session and plain request to those APIs won't work anymore (it will be redirected instead). 

No need to change the autocomplete fields because session is already embedded in request.

**Comment by ajeygore** [comment] 2018-04-27 05:57
Marking this as complete.

**Closed by ajeygore** 2018-04-27 05:57 UTC
